python main.py\
	--data_path '../data/'\
	--evaluation_file_val '../output/val_2_11.csv'\
	--evaluation_file '../output/test_2_11.csv'\
	--iterr 1\
	--stats_include 2\
	--rdm 11\
	--year 2018\
	--cuda 0\
